export { default as DefaultLayout } from './DefaultLayout.vue'
export { default as AuthLayout } from './AuthLayout.vue'
export { default as AdminLayout } from './AdminLayout.vue'
export { default as PlatformAdminLayout } from './PlatformAdminLayout.vue'
export { default as MobileLayout } from './MobileLayout.vue'
